name: Publish to NPM
on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: npm install
      - name: Bump Version
        run: |
          initialTag=${{ github.event.release.tag_name }}
          tag="${initialTag//[v]/}"
          ./bump-version.sh $tag
      - name: Build library
        run: npm run build
      - name: Publish to NPM
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        tag="${{ github.event.release.tag_name }}"
        ./publish.sh "$tag"